name: hroom
description: Decrypt Chrome passwords on Linux.
version: 1.0.0

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  cryptography: ^2.7.0
  dbus: ^0.7.10
  encrypt: ^5.0.3
  sqlite3: ^2.5.0
  xdg_directories: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
